// <auto-generated />
using System;
using Huayu.Oms.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Huayu.Oms.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OmsContext))]
    [Migration("20220801084326_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Huayu.Oms.Domain.AgregatesModel.TenantAggregate.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastModified")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaxpayerId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("TenantStatusId")
                        .HasColumnType("int")
                        .HasColumnName("TenantStatusId1");

                    b.Property<int>("_tenantStatusId")
                        .HasColumnType("int")
                        .HasColumnName("TenantStatusId");

                    b.HasKey("Id");

                    b.HasIndex("TenantStatusId");

                    b.ToTable("tenants", "oms");
                });

            modelBuilder.Entity("Huayu.Oms.Domain.AgregatesModel.TenantAggregate.TenantStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("tenantstatus", "oms");
                });

            modelBuilder.Entity("Huayu.Oms.Domain.AgregatesModel.TenantAggregate.Tenant", b =>
                {
                    b.HasOne("Huayu.Oms.Domain.AgregatesModel.TenantAggregate.TenantStatus", "TenantStatus")
                        .WithMany()
                        .HasForeignKey("TenantStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Huayu.Oms.Domain.AgregatesModel.TenantAggregate.Address", "Address", b1 =>
                        {
                            b1.Property<int>("TenantId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants", "oms");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("TenantStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
